Blog Post:
  - changed-files:
      - any-glob-to-any-file: content/**.md
Personal:
  - changed-files:
      - any-glob-to-any-file: content/personal/**.md
Security:
  - changed-files:
      - any-glob-to-any-file: content/blog/**.md
