---
name: Check any branch for The Broader Picture Blog

on: push

jobs:
  test-language:
    name: Test for biased language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.2
      - name: Install Alex
        run: npm install alex@9.1.0 --global
      - name: Test content with alex
        run: alex ./content
  test-complexity:
    name: Get report on language complexity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install language complexity tools
        run: python3 -m pip install textstat-cli==1.1.3
      - name: Get language complexity report
        run: python3 -m textstat_cli ./content
  test-spelling:
    name: Use GrammarBot to check for spelling and grammar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install grammaerbot CLI tool
        run: python3 -m pip install hemoglobin==0.0.2
      - name: Get grammarbot report
        run: python3 -m hemoglobin ${{ secrets.GRAMMARBOT_APIKEY }} ./content
  grammar-check:
    name: Use write-good to check usage of language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.2
      - name: Install write-good
        run: npm install write-good@1.0.8 --global
      - name: Test content with write-good
        run: write-good --help
