---
name: Check New Posts

on:
  pull_request:
    branches:
      - main
    paths:
      - "content/**.md"

jobs:
  markdownlint:
    name: Check markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci --include dev
      - name: Test content with markdownlint
        run: |
          npx markdownlint --config ./markdownlint.config.json content/**.md
  test-language:
    name: Test for biased language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci --include dev
      - name: Test content with alex
        run: |
          alex content/**.md
  test-complexity:
    name: Get report on language complexity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: "auto"
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"
      - name: Get language complexity report
        run: |
          uv run textstat_cli content/**.md
  test-spelling:
    name: Use GrammarBot to check for spelling and grammar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: "auto"
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"
      - name: Get grammarbot report
        run: |
          uv run hemoglobin ${{ secrets.GRAMMARBOT_APIKEY }} content/**.md
  grammar-check:
    name: Use write-good to check usage of language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci --include dev
      - name: Test content with write-good
        continue-on-error: true
        run: |
          write-good --parse content/**.md
