---
name: Check New Posts

on:
  pull_request:
    branches:
      - main
    paths:
      - "content/**.md"

jobs:
  markdownlint:
    name: Check markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci --include dev
      - name: Find changed files
        id: changed-files
        uses: dorny/paths-filter@v4
        with:
          list-files: shell
          base: main
          filters: |
            content:
              - added|modified: 'content/**/*.md'
      - name: Test content with markdownlint
        run: |
          npx markdownlint --config ./markdownlint.config.json ${{ steps.changed-files.outputs.content_files }}
  test-language:
    name: Test for biased language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci --include dev
      - name: Find changed files
        id: changed-files
        uses: dorny/paths-filter@v4
        with:
          list-files: shell
          base: main
          filters: |
            content:
              - added|modified: 'content/**/*.md'
      - name: Test content with alex
        run: |
          npm exec -- alex ${{ steps.changed-files.outputs.content_files }}
  test-complexity:
    name: Get report on language complexity
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: "auto"
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"
      - name: Find changed files
        id: changed-files
        uses: dorny/paths-filter@v4
        with:
          list-files: shell
          base: main
          filters: |
            content:
              - added|modified: 'content/**/*.md'
      - name: Get language complexity report
        id: complexity-report
        run: |
            {
              echo "report<<EOF"
                  uv run textstat_cli ${{ steps.changed-files.outputs.content_files }}
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
      - name: Add comment to PR
        uses: mshick/add-pr-comment@v3
        with:
          message: ${{ steps.complexity-report.outputs.report }}
  grammar-check:
    name: Use write-good to check usage of language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci --include dev
      - name: Find changed files
        id: changed-files
        uses: dorny/paths-filter@v4
        with:
          list-files: shell
          base: main
          filters: |
            content:
              - added|modified: 'content/**/*.md'
      - name: Test content with write-good
        continue-on-error: true
        run: |
          write-good --parse ${{ steps.changed-files.outputs.content_files }}
