---
name: Deploy The Broader Picture Blog

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.136.5"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4 # or specific "vX.X.X" version tag for this action
        with:
          path: ./public/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Add published pages to WayBack Machine
        run: |
          curl 'https://web.archive.org/save/https://matt.copperwaite.net' -X POST -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'url=https%3A%2F%2Fmatt.copperwaite.net&capture_all=on'
          curl 'https://web.archive.org/save/https://matt.copperwaite.net/blog' -X POST -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'url=https%3A%2F%2Fmatt.copperwaite.net%2Fblog&capture_all=on'
          curl 'https://web.archive.org/save/https://matt.copperwaite.net/showcase' -X POST -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'url=https%3A%2F%2Fmatt.copperwaite.net%2Fshowcase&capture_all=on'
