---
name: Deploy The Broader Picture Blog

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.1'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Recreate CNAME file
        run: echo "matt.copperwaite.net" > ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Wait for GitHub cache to update
        run: sleep 60
      - name: Add published pages to WayBack Machine
        run: |
          curl 'https://web.archive.org/save/https://matt.copperwaite.net' -X POST -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'url=https%3A%2F%2Fmatt.copperwaite.net&capture_all=on'
          curl 'https://web.archive.org/save/https://matt.copperwaite.net/blog' -X POST -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'url=https%3A%2F%2Fmatt.copperwaite.net%2Fblog&capture_all=on'
          curl 'https://web.archive.org/save/https://matt.copperwaite.net/showcase' -X POST -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'url=https%3A%2F%2Fmatt.copperwaite.net%2Fshowcase&capture_all=on'
